// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleTax.Web.Data;

#nullable disable

namespace VehicleTax.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901074725_AddPaymentReferenceNo")]
    partial class AddPaymentReferenceNo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VehicleTax.Web.Models.CarType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CarTypes");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.Checkpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.GolisAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("AmountMismatchAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("AmountMismatchCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("AuditPeriodFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("AuditPeriodTo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Difference")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FinalizedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MatchedAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("NotInSystemAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("NotInSystemCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("StatementNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("StatementTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("StatementTransactionCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SystemOnlyAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SystemOnlyCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalGolisAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TotalGolisTransactions")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSystemAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TotalSystemTransactions")
                        .HasColumnType("int");

                    b.Property<string>("UploadedFilePath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FinalizedByUserId");

                    b.ToTable("GolisAudits");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.GolisTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AuditPeriod")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("EnteredByUserId")
                        .HasColumnType("int");

                    b.Property<int>("GolisAuditId")
                        .HasColumnType("int");

                    b.Property<string>("GolisStatementNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("GolisTransactionReference")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MatchedPaymentId")
                        .HasColumnType("int");

                    b.Property<string>("MatchedReceiptNumber")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("MatchedSystemAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("ReconciliationStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan?>("TransactionTime")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("EnteredByUserId");

                    b.HasIndex("GolisTransactionReference");

                    b.HasIndex("MatchedPaymentId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("GolisAuditId", "ReconciliationStatus");

                    b.ToTable("GolisTransactions");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CarTypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RevenueAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarTypeId");

                    b.HasIndex("RevenueAccountId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("CheckpointId")
                        .HasColumnType("int");

                    b.Property<int?>("CollectorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReverted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MovementId")
                        .HasColumnType("int");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaidBy")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<int?>("ReceiptReferenceId")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceNo")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("RevertReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RevertedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RevertedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("longtext");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointId");

                    b.HasIndex("CollectorId");

                    b.HasIndex("MovementId");

                    b.HasIndex("ReceiptReferenceId");

                    b.HasIndex("ReferenceNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Payments_ReferenceNo");

                    b.HasIndex("RevertedByUserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.PaymentReferenceSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastAssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LastReferenceNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaymentReferenceSequences");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.ReceiptReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CancelledBy")
                        .HasColumnType("longtext");

                    b.Property<string>("CancelledReason")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsedBy")
                        .HasColumnType("longtext");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("ReceiptReferences");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.RevenueAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AccountCode")
                        .IsUnique();

                    b.ToTable("RevenueAccounts");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.TaxAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MovementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarTypeId");

                    b.HasIndex("MovementId");

                    b.ToTable("TaxAmounts");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CheckpointId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointId");

                    b.HasIndex("Username")
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CarTypeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.GolisAudit", b =>
                {
                    b.HasOne("VehicleTax.Web.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VehicleTax.Web.Models.User", "FinalizedByUser")
                        .WithMany()
                        .HasForeignKey("FinalizedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("FinalizedByUser");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.GolisTransaction", b =>
                {
                    b.HasOne("VehicleTax.Web.Models.User", "EnteredByUser")
                        .WithMany()
                        .HasForeignKey("EnteredByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VehicleTax.Web.Models.GolisAudit", "GolisAudit")
                        .WithMany("GolisTransactions")
                        .HasForeignKey("GolisAuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTax.Web.Models.Payment", "MatchedPayment")
                        .WithMany()
                        .HasForeignKey("MatchedPaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VehicleTax.Web.Models.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EnteredByUser");

                    b.Navigation("GolisAudit");

                    b.Navigation("MatchedPayment");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.Movement", b =>
                {
                    b.HasOne("VehicleTax.Web.Models.CarType", "CarType")
                        .WithMany()
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTax.Web.Models.RevenueAccount", "RevenueAccount")
                        .WithMany("Movements")
                        .HasForeignKey("RevenueAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CarType");

                    b.Navigation("RevenueAccount");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.Payment", b =>
                {
                    b.HasOne("VehicleTax.Web.Models.Checkpoint", "Checkpoint")
                        .WithMany()
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VehicleTax.Web.Models.User", "Collector")
                        .WithMany()
                        .HasForeignKey("CollectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VehicleTax.Web.Models.Movement", "Movement")
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleTax.Web.Models.ReceiptReference", "ReceiptReference")
                        .WithMany()
                        .HasForeignKey("ReceiptReferenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VehicleTax.Web.Models.User", "RevertedByUser")
                        .WithMany()
                        .HasForeignKey("RevertedByUserId");

                    b.HasOne("VehicleTax.Web.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checkpoint");

                    b.Navigation("Collector");

                    b.Navigation("Movement");

                    b.Navigation("ReceiptReference");

                    b.Navigation("RevertedByUser");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.ReceiptReference", b =>
                {
                    b.HasOne("VehicleTax.Web.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.TaxAmount", b =>
                {
                    b.HasOne("VehicleTax.Web.Models.CarType", "CarType")
                        .WithMany()
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTax.Web.Models.Movement", "Movement")
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarType");

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.User", b =>
                {
                    b.HasOne("VehicleTax.Web.Models.Checkpoint", "Checkpoint")
                        .WithMany("Users")
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Checkpoint");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.Vehicle", b =>
                {
                    b.HasOne("VehicleTax.Web.Models.CarType", "CarType")
                        .WithMany()
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarType");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.Checkpoint", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.GolisAudit", b =>
                {
                    b.Navigation("GolisTransactions");
                });

            modelBuilder.Entity("VehicleTax.Web.Models.RevenueAccount", b =>
                {
                    b.Navigation("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
