using System.Data;
using Microsoft.EntityFrameworkCore;
using VehicleTax.Web.Data;
using VehicleTax.Web.Models;

namespace VehicleTax.Web.Services
{
    /// <summary>
    /// Provides transaction-safe, sequential audit Reference Number generation for payments.
    /// </summary>
    /// <remarks>
    /// Reference numbers are generated by the backend/database — NEVER by the Flutter
    /// client. Generation uses a dedicated sequence table with an atomic UPDATE
    /// (row-level exclusive lock) so that concurrent collectors recording payments
    /// simultaneously never receive duplicate or out-of-order numbers.
    ///
    /// No unsafe MAX(ReferenceNo) + 1 pattern is used.
    /// </remarks>
    public interface IPaymentReferenceService
    {
        Task<int> GetNextReferenceNoAsync();
        int GetNextReferenceNo();
    }

    public class PaymentReferenceService : IPaymentReferenceService
    {
        private readonly AppDbContext _context;

        public PaymentReferenceService(AppDbContext context)
        {
            _context = context;
        }

        // ── Async ──────────────────────────────────────────────────────
        public async Task<int> GetNextReferenceNoAsync()
        {
            await using var tx = await _context.Database.BeginTransactionAsync(IsolationLevel.ReadCommitted);

            // Ensure the single seed row exists (idempotent)
            await _context.Database.ExecuteSqlRawAsync(
                @"INSERT IGNORE INTO PaymentReferenceSequences (Id, LastReferenceNo) VALUES (1, 0)");

            // Atomically increment. MySQL's UPDATE acquires an exclusive row lock,
            // so concurrent callers serialize on this single row — no two transactions
            // can ever read the same LastReferenceNo value.
            await _context.Database.ExecuteSqlRawAsync(
                @"UPDATE PaymentReferenceSequences
                    SET LastReferenceNo = LastReferenceNo + 1,
                        LastAssignedAt = NOW()
                  WHERE Id = 1");

            // Read back the new value within the same transaction
            var seq = await _context.PaymentReferenceSequences
                .FromSqlRaw(@"SELECT Id, LastReferenceNo, LastAssignedAt
                              FROM PaymentReferenceSequences WHERE Id = 1")
                .AsNoTracking()
                .FirstOrDefaultAsync();

            await tx.CommitAsync();

            return seq!.LastReferenceNo;
        }

        // ── Sync (used by Razor Page handlers) ─────────────────────────
        public int GetNextReferenceNo()
        {
            using var tx = _context.Database.BeginTransaction(IsolationLevel.ReadCommitted);

            _context.Database.ExecuteSqlRaw(
                @"INSERT IGNORE INTO PaymentReferenceSequences (Id, LastReferenceNo) VALUES (1, 0)");

            _context.Database.ExecuteSqlRaw(
                @"UPDATE PaymentReferenceSequences
                    SET LastReferenceNo = LastReferenceNo + 1,
                        LastAssignedAt = NOW()
                  WHERE Id = 1");

            var seq = _context.PaymentReferenceSequences
                .FromSqlRaw(@"SELECT Id, LastReferenceNo, LastAssignedAt
                              FROM PaymentReferenceSequences WHERE Id = 1")
                .AsNoTracking()
                .FirstOrDefault();

            tx.Commit();

            return seq!.LastReferenceNo;
        }
    }
}